import { z } from 'zod';
import { isHex } from './color';
import {
  COLOR_KEYS,
  colorSetToDeclarations,
  FONT_KEYS,
  FONT_STACKS,
  RADIUS_VALUES,
  type ColorKey,
} from './theme-values';

// The plain keys, presets and contrast helpers are in theme-values.ts, which client code imports
// directly.
export * from './theme-values';

export const hexColor = z
  .string()
  .refine(isHex, 'Must be a 6-digit hex colour like #1a2b3c')
  .transform((s) => s.toLowerCase());

export const colorSetSchema = z.object(
  Object.fromEntries(COLOR_KEYS.map((k) => [k, hexColor])) as Record<ColorKey, typeof hexColor>,
);
export type ColorSet = z.infer<typeof colorSetSchema>;

/** Upload keys are generated by the server; never arbitrary URLs. */
export const uploadKey = z
  .string()
  .regex(/^u\/[a-z0-9]{8,40}\.(webp|png|jpg|gif)$/, 'Invalid upload reference');

export const themeSchema = z.object({
  v: z.literal(1),
  preset: z.string().max(32).optional(),
  light: colorSetSchema,
  dark: colorSetSchema,
  defaultScheme: z.enum(['auto', 'light', 'dark']).default('auto'),
  radius: z.enum(['none', 'sm', 'md', 'lg', 'xl']).default('md'),
  fontBody: z.enum(FONT_KEYS).default('inter'),
  fontHeading: z.enum(FONT_KEYS).default('inter'),
  headerStyle: z.enum(['banner', 'compact', 'split']).default('banner'),
  bannerKey: uploadKey.optional(),
  bannerFocalY: z.number().int().min(0).max(100).default(50),
  iconKey: uploadKey.optional(),
  backgroundKey: uploadKey.optional(),
  backgroundDim: z.number().int().min(0).max(95).default(70),
});
export type Theme = z.infer<typeof themeSchema>;

/** Selectors are chosen by our code, never by users. */
export type ThemeSelector = ':root' | '[data-community-theme]' | '[data-theme-preview]';
export type ThemeLayer = 'mx-tokens' | 'mx-community';

function under(prefix: string, selector: ThemeSelector): string {
  return selector === ':root' ? prefix : `${prefix} ${selector}`;
}

/**
 * Emit CSS for a theme inside a cascade layer. Site defaults use `mx-tokens`, communities use
 * `mx-community`. User preferences live in the last layer (`mx-prefs`) and always win.
 */
export function themeToCss(
  input: Theme,
  selector: ThemeSelector = '[data-community-theme]',
  layer: ThemeLayer = 'mx-community',
): string {
  const theme = themeSchema.parse(input);
  // --mx-l / --mx-d say which colour set is showing ("initial" = this one), so things drawn
  // for both sets (like role name effects) can pick theirs. See .mx-name in globals.css.
  const light = `color-scheme:light;--mx-l:initial;--mx-d: ;${colorSetToDeclarations(theme.light)}`;
  const dark = `color-scheme:dark;--mx-l: ;--mx-d:initial;${colorSetToDeclarations(theme.dark)}`;
  const shared = [
    `--mx-radius:${RADIUS_VALUES[theme.radius]}`,
    `--mx-font-body:${FONT_STACKS[theme.fontBody]}`,
    `--mx-font-heading:${FONT_STACKS[theme.fontHeading]}`,
  ].join(';');

  const base = theme.defaultScheme === 'dark' ? dark : light;
  const rules = [`${selector}{${shared};${base}}`];
  if (theme.defaultScheme === 'dark') {
    rules.push(`${under('html[data-scheme="light"]', selector)}{${light}}`);
  } else {
    rules.push(`${under('html[data-scheme="dark"]', selector)}{${dark}}`);
  }
  if (theme.defaultScheme === 'auto') {
    rules.push(
      `@media (prefers-color-scheme: dark){${under('html[data-scheme="system"]', selector)}{${dark}}}`,
    );
  }
  return `@layer ${layer}{${rules.join('')}}`;
}
