/** Seed catalog of popular games. Communities and servers can reference these. */
export const GAMES: {
  id: string;
  name: string;
  protocol?: string;
  steamAppId?: number;
  color?: string;
  aliases?: string[];
}[] = [
  { id: 'minecraft', name: 'Minecraft', protocol: 'minecraft', color: '#5b8731', aliases: ['mc'] },
  { id: 'rust', name: 'Rust', protocol: 'rust', steamAppId: 252490, color: '#cd412b' },
  {
    id: 'cs2',
    name: 'Counter-Strike 2',
    protocol: 'cs2',
    steamAppId: 730,
    color: '#de9b35',
    aliases: ['csgo', 'counter strike'],
  },
  {
    id: 'gta-v',
    name: 'Grand Theft Auto V',
    protocol: 'fivem',
    steamAppId: 271590,
    color: '#2d7d46',
    aliases: ['fivem', 'gta 5', 'gta rp'],
  },
  {
    id: 'ark',
    name: 'ARK: Survival Evolved',
    protocol: 'ark',
    steamAppId: 346110,
    color: '#4a7aa8',
  },
  { id: 'gmod', name: "Garry's Mod", protocol: 'gmod', steamAppId: 4000, color: '#1f8fe5' },
  { id: 'tf2', name: 'Team Fortress 2', protocol: 'tf2', steamAppId: 440, color: '#b8383b' },
  { id: 'valheim', name: 'Valheim', protocol: 'valheim', steamAppId: 892970, color: '#7f6b4d' },
  { id: 'terraria', name: 'Terraria', protocol: 'terraria', steamAppId: 105600, color: '#3a8f3f' },
  { id: 'palworld', name: 'Palworld', steamAppId: 1623730, color: '#3aa0d8' },
  {
    id: '7-days-to-die',
    name: '7 Days to Die',
    protocol: 'sevendays',
    steamAppId: 251570,
    color: '#8b1e1e',
  },
  { id: 'dayz', name: 'DayZ', protocol: 'dayz', steamAppId: 221100, color: '#5c5c4a' },
  { id: 'squad', name: 'Squad', protocol: 'squad', steamAppId: 393380, color: '#5f7a3a' },
  { id: 'valorant', name: 'VALORANT', color: '#ff4655' },
  { id: 'league-of-legends', name: 'League of Legends', color: '#c89b3c', aliases: ['lol'] },
  { id: 'fortnite', name: 'Fortnite', color: '#9d4dbb' },
  { id: 'apex-legends', name: 'Apex Legends', steamAppId: 1172470, color: '#da292a' },
  { id: 'overwatch-2', name: 'Overwatch 2', color: '#f99e1a' },
  { id: 'dota-2', name: 'Dota 2', steamAppId: 570, color: '#a72714' },
  { id: 'destiny-2', name: 'Destiny 2', steamAppId: 1085660, color: '#3a5f8c' },
  { id: 'world-of-warcraft', name: 'World of Warcraft', color: '#f8b700', aliases: ['wow'] },
  {
    id: 'final-fantasy-xiv',
    name: 'Final Fantasy XIV',
    steamAppId: 39210,
    color: '#6a4ca8',
    aliases: ['ffxiv'],
  },
  {
    id: 'path-of-exile-2',
    name: 'Path of Exile 2',
    steamAppId: 2694490,
    color: '#a3701f',
    aliases: ['poe2'],
  },
  { id: 'helldivers-2', name: 'Helldivers 2', steamAppId: 553850, color: '#f2c200' },
  {
    id: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    steamAppId: 1086940,
    color: '#7a2b2b',
    aliases: ['bg3'],
  },
  { id: 'elden-ring', name: 'Elden Ring', steamAppId: 1245620, color: '#b09a5b' },
  { id: 'stardew-valley', name: 'Stardew Valley', steamAppId: 413150, color: '#6fa43a' },
  { id: 'rocket-league', name: 'Rocket League', steamAppId: 252950, color: '#1a73e8' },
  { id: 'among-us', name: 'Among Us', steamAppId: 945360, color: '#c51111' },
  { id: 'roblox', name: 'Roblox', protocol: 'roblox', color: '#e2231a' },
  { id: 'deep-rock-galactic', name: 'Deep Rock Galactic', steamAppId: 548430, color: '#d17d1b' },
  { id: 'satisfactory', name: 'Satisfactory', steamAppId: 526870, color: '#f39c12' },
  // Games whose servers Game Central can check (see SERVER_PROTOCOLS).
  { id: 'arma-3', name: 'Arma 3', protocol: 'arma3', steamAppId: 107410, color: '#6b7a3a' },
  {
    id: 'arma-reforger',
    name: 'Arma Reforger',
    protocol: 'arma-reforger',
    steamAppId: 1874880,
    color: '#55663b',
  },
  {
    id: 'conan-exiles',
    name: 'Conan Exiles',
    protocol: 'conan',
    steamAppId: 440900,
    color: '#a6542a',
  },
  {
    id: 'counter-strike-source',
    name: 'Counter-Strike: Source',
    protocol: 'css',
    steamAppId: 240,
    color: '#c8902f',
    aliases: ['css'],
  },
  {
    id: 'counter-strike-1-6',
    name: 'Counter-Strike 1.6',
    protocol: 'cs16',
    steamAppId: 10,
    color: '#b0802c',
    aliases: ['cs 1.6', 'cs16'],
  },
  {
    id: 'left-4-dead-2',
    name: 'Left 4 Dead 2',
    protocol: 'l4d2',
    steamAppId: 550,
    color: '#a32b1f',
    aliases: ['l4d2'],
  },
  {
    id: 'insurgency',
    name: 'Insurgency',
    protocol: 'insurgency',
    steamAppId: 222880,
    color: '#7a6a45',
  },
  {
    id: 'insurgency-sandstorm',
    name: 'Insurgency: Sandstorm',
    protocol: 'sandstorm',
    steamAppId: 581320,
    color: '#b5813c',
  },
  {
    id: 'day-of-defeat-source',
    name: 'Day of Defeat: Source',
    protocol: 'dods',
    steamAppId: 300,
    color: '#6d6141',
    aliases: ['dods'],
  },
  {
    id: 'no-more-room-in-hell',
    name: 'No More Room in Hell',
    protocol: 'nmrih',
    steamAppId: 224260,
    color: '#7c1d1d',
    aliases: ['nmrih'],
  },
  {
    id: 'hell-let-loose',
    name: 'Hell Let Loose',
    protocol: 'hll',
    steamAppId: 686810,
    color: '#8a6d3b',
    aliases: ['hll'],
  },
  {
    id: 'squad-44',
    name: 'Squad 44',
    protocol: 'post-scriptum',
    steamAppId: 736220,
    color: '#5a5a3c',
    aliases: ['post scriptum'],
  },
  { id: 'mordhau', name: 'Mordhau', protocol: 'mordhau', steamAppId: 629760, color: '#9b2c2c' },
  {
    id: 'killing-floor-2',
    name: 'Killing Floor 2',
    protocol: 'kf2',
    steamAppId: 232090,
    color: '#8c1c13',
    aliases: ['kf2'],
  },
  {
    id: 'project-zomboid',
    name: 'Project Zomboid',
    protocol: 'zomboid',
    steamAppId: 108600,
    color: '#7d2b2b',
    aliases: ['pz'],
  },
  { id: 'unturned', name: 'Unturned', protocol: 'unturned', steamAppId: 304930, color: '#4f8a3c' },
  { id: 'v-rising', name: 'V Rising', protocol: 'v-rising', steamAppId: 1604030, color: '#a4161a' },
  {
    id: 'enshrouded',
    name: 'Enshrouded',
    protocol: 'enshrouded',
    steamAppId: 1203620,
    color: '#3f7f8f',
  },
  {
    id: 'the-forest',
    name: 'The Forest',
    protocol: 'the-forest',
    steamAppId: 242760,
    color: '#3d5a3a',
  },
  {
    id: 'sons-of-the-forest',
    name: 'Sons of the Forest',
    protocol: 'sons-of-the-forest',
    steamAppId: 1326470,
    color: '#4b6b3a',
    aliases: ['sotf'],
  },
  { id: 'soulmask', name: 'Soulmask', protocol: 'soulmask', steamAppId: 2646460, color: '#8a6a2f' },
  { id: 'icarus', name: 'Icarus', protocol: 'icarus', steamAppId: 1149460, color: '#c76a2b' },
  {
    id: 'the-front',
    name: 'The Front',
    protocol: 'the-front',
    steamAppId: 2285150,
    color: '#6f7d4a',
  },
  {
    id: 'abiotic-factor',
    name: 'Abiotic Factor',
    protocol: 'abiotic-factor',
    steamAppId: 427410,
    color: '#3a9a8f',
  },
  {
    id: 'hurtworld',
    name: 'Hurtworld',
    protocol: 'hurtworld',
    steamAppId: 393420,
    color: '#9a5a2a',
  },
  {
    id: 'space-engineers',
    name: 'Space Engineers',
    protocol: 'space-engineers',
    steamAppId: 244850,
    color: '#3d6f9a',
  },
  { id: 'avorion', name: 'Avorion', protocol: 'avorion', steamAppId: 445220, color: '#2f6fb0' },
  {
    id: 'starbound',
    name: 'Starbound',
    protocol: 'starbound',
    steamAppId: 211820,
    color: '#4b3f8f',
  },
  {
    id: 'barotrauma',
    name: 'Barotrauma',
    protocol: 'barotrauma',
    steamAppId: 602960,
    color: '#2b5d6b',
  },
  {
    id: 'dont-starve-together',
    name: "Don't Starve Together",
    protocol: 'dst',
    steamAppId: 322330,
    color: '#7a5230',
    aliases: ['dst'],
  },
  {
    id: 'euro-truck-simulator-2',
    name: 'Euro Truck Simulator 2',
    protocol: 'ets2',
    steamAppId: 227300,
    color: '#2f6db5',
    aliases: ['ets2'],
  },
  {
    id: 'gta-san-andreas',
    name: 'Grand Theft Auto: San Andreas',
    protocol: 'samp',
    steamAppId: 12120,
    color: '#c4802f',
    aliases: ['samp', 'sa-mp', 'open.mp', 'gta sa'],
  },
  {
    id: 'call-of-duty-4',
    name: 'Call of Duty 4: Modern Warfare',
    protocol: 'cod4',
    steamAppId: 7940,
    color: '#59683a',
    aliases: ['cod4'],
  },
  {
    id: 'battlefield-4',
    name: 'Battlefield 4',
    protocol: 'bf4',
    steamAppId: 1238860,
    color: '#e0662f',
    aliases: ['bf4'],
  },
  // Popular games people build communities around (no server status).
  {
    id: 'ark-survival-ascended',
    name: 'ARK: Survival Ascended',
    steamAppId: 2399830,
    color: '#3f7ab8',
    aliases: ['asa'],
  },
  { id: 'factorio', name: 'Factorio', steamAppId: 427520, color: '#d07b2b' },
  { id: 'lethal-company', name: 'Lethal Company', steamAppId: 1966720, color: '#b23a2a' },
  { id: 'phasmophobia', name: 'Phasmophobia', steamAppId: 739630, color: '#5b6b8a' },
  { id: 'sea-of-thieves', name: 'Sea of Thieves', steamAppId: 1172620, color: '#1f8a8a' },
  { id: 'warframe', name: 'Warframe', steamAppId: 230410, color: '#9c8b5a' },
  { id: 'pubg', name: 'PUBG: Battlegrounds', steamAppId: 578080, color: '#f2a900' },
  {
    id: 'rainbow-six-siege',
    name: 'Rainbow Six Siege',
    steamAppId: 359550,
    color: '#3a6fb0',
    aliases: ['r6', 'siege'],
  },
  { id: 'war-thunder', name: 'War Thunder', steamAppId: 236390, color: '#c0392b' },
  { id: 'hunt-showdown', name: 'Hunt: Showdown 1896', steamAppId: 594650, color: '#8a2a1f' },
  { id: 'dead-by-daylight', name: 'Dead by Daylight', steamAppId: 381210, color: '#8b0000' },
  { id: 'marvel-rivals', name: 'Marvel Rivals', steamAppId: 2767030, color: '#e8b923' },
  {
    id: 'monster-hunter-wilds',
    name: 'Monster Hunter Wilds',
    steamAppId: 2246340,
    color: '#b5762b',
  },
  { id: 'black-desert', name: 'Black Desert', steamAppId: 582660, color: '#a07b3b' },
  { id: 'lost-ark', name: 'Lost Ark', steamAppId: 1599340, color: '#3b5fa0' },
  {
    id: 'guild-wars-2',
    name: 'Guild Wars 2',
    steamAppId: 1284210,
    color: '#b31b1b',
    aliases: ['gw2'],
  },
  {
    id: 'elder-scrolls-online',
    name: 'The Elder Scrolls Online',
    steamAppId: 306130,
    color: '#a38a5b',
    aliases: ['eso'],
  },
  { id: 'eve-online', name: 'EVE Online', steamAppId: 8500, color: '#2a6fb5' },
  {
    id: 'old-school-runescape',
    name: 'Old School RuneScape',
    steamAppId: 1343370,
    color: '#b88c3a',
    aliases: ['osrs'],
  },
  { id: 'battlefield-2042', name: 'Battlefield 2042', steamAppId: 1517290, color: '#2f7fd0' },
  { id: 'the-finals', name: 'The Finals', steamAppId: 2073850, color: '#d32f2f' },
  { id: 'deadlock', name: 'Deadlock', steamAppId: 1422450, color: '#b38a4a' },
  {
    id: 'call-of-duty',
    name: 'Call of Duty',
    steamAppId: 1938090,
    color: '#4caf50',
    aliases: ['cod', 'warzone'],
  },
  { id: 'fall-guys', name: 'Fall Guys', steamAppId: 1097150, color: '#e85fa8' },
  { id: 'brawlhalla', name: 'Brawlhalla', steamAppId: 291550, color: '#3a8fd0' },
  {
    id: 'warhammer-40k-darktide',
    name: 'Warhammer 40,000: Darktide',
    steamAppId: 1361210,
    color: '#7a6a3a',
    aliases: ['darktide'],
  },
  { id: 'rimworld', name: 'RimWorld', steamAppId: 294100, color: '#8a6a3a' },
  { id: 'genshin-impact', name: 'Genshin Impact', color: '#4a90c2' },
  { id: 'hytale', name: 'Hytale', color: '#3b82c4' },
  { id: 'other', name: 'Other / multiple games', color: '#6b7280' },
];
